// generated by /dev-process-toolkit:setup — Bun zero-match workaround (see examples/bun-typescript.md)
import { test, expect } from "bun:test";

test("placeholder — delete once the project ships its first real test", () => {
  expect(1 + 1).toBe(2);
});
